"""
NIELIT Ropar - Professional Diabetes Risk Assessment System
Classification Demo - Release v1.0
Target Dataset: PIMA Indian Diabetes Dataset
Author: Anita Budhiraja
"""

import os
import time
import tempfile
import logging
from datetime import datetime
from pathlib import Path
import pytz  # Added for Timezone management

import streamlit as st
import pandas as pd
import numpy as np
import joblib
import plotly.graph_objects as go
import plotly.express as px
from huggingface_hub import HfApi, hf_hub_download, create_repo


# 1. Page Configuration

st.set_page_config(
    page_title="NIELIT Diabetes Assessment v1.0",
    page_icon="🏥",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# 2. CSS Styling (Mobile Responsive)

st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap');

    :root {
        --primary-color: #0F52BA;
        --bg-color: #F4F7F9;
        --text-dark: #1F2937;
    }

    /* Base App Styling */
    html, body, [class*="css"] {
        font-family: 'Inter', sans-serif;
    }
    
    .stApp {
        background-color: var(--bg-color);
        color: var(--text-dark);
    }

    /* --- CRITICAL MOBILE & DARK MODE INPUT FIX --- */
    /* Target specifically the input elements generated by Streamlit/BaseWeb */
    input[type="text"], input[type="number"], .stNumberInput input, .stTextInput input {
        color: #1F2937 !important;           /* Force Dark Grey Text */
        background-color: #ffffff !important; /* Force White Background */
        -webkit-text-fill-color: #1F2937 !important; /* CRITICAL for iOS Safari Dark Mode */
        caret-color: #1F2937 !important;      /* Cursor Color */
        font-weight: 500 !important;
    }

    /* Force the container of the input to be white with a border */
    div[data-baseweb="input"], div[data-baseweb="base-input"] {
        background-color: #ffffff !important;
        border: 1px solid #D1D5DB !important;
        border-radius: 6px !important;
    }

    /* Labels above inputs */
    .stNumberInput label, .stTextInput label {
        color: #374151 !important; /* Dark Grey Label */
        font-weight: 600 !important;
        font-size: 0.9rem !important;
    }

    /* --- CARD STYLING --- */
    .content-card {
        background: white;
        border-radius: 12px;
        padding: 1.5rem;
        margin-bottom: 1.5rem;
        box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);
        border: 1px solid #E5E7EB;
    }

    /* Header Styling */
    .header-container {
        background: white;
        padding: 2rem;
        border-radius: 12px;
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05);
        margin-bottom: 2rem;
        border-top: 5px solid var(--primary-color);
    }

    .header-title {
        color: #111827;
        font-size: 1.75rem;
        font-weight: 700;
        margin: 0;
    }

    /* Stat Boxes */
    .stat-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
        gap: 1rem;
        margin-bottom: 2rem;
    }
    .stat-box {
        background: white;
        padding: 1.25rem;
        border-radius: 10px;
        box-shadow: 0 1px 2px rgba(0,0,0,0.05);
        border-left: 4px solid var(--primary-color);
    }
    .stat-value { font-size: 1.8rem; font-weight: 700; color: #111827; }
    .stat-label { font-size: 0.875rem; color: #6B7280; font-weight: 500; }

    /* Button Styling */
    .stButton > button {
        background: linear-gradient(135deg, #0F52BA 0%, #2563EB 100%);
        color: white !important;
        border: none;
        padding: 0.75rem 1.5rem;
        border-radius: 8px;
        font-weight: 600;
        width: 100%;
        transition: all 0.2s;
    }
    .stButton > button:hover {
        transform: translateY(-2px);
        box-shadow: 0 4px 12px rgba(37, 99, 235, 0.3);
    }

    /* Result Cards */
    .risk-high {
        background: linear-gradient(135deg, #DC2626 0%, #991B1B 100%);
        color: white; padding: 2rem; border-radius: 12px; text-align: center;
    }
    .risk-low {
        background: linear-gradient(135deg, #059669 0%, #047857 100%);
        color: white; padding: 2rem; border-radius: 12px; text-align: center;
    }

    /* Hide standard Streamlit chrome */
    #MainMenu {visibility: hidden;}
    footer {visibility: hidden;}
    header {visibility: hidden;}
</style>
""", unsafe_allow_html=True)

# 3. Backend Logic (Timezone Aware)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

# Constants
MODEL_DIR = Path("models")
MODEL_FILE = MODEL_DIR / "diabetes.sav"
SCALER_FILE = MODEL_DIR / "scaler.sav"
MEDIANS_FILE = MODEL_DIR / "medians.sav"
HF_USERNAME = "nielitropar"
DATASET_REPO = f"{HF_USERNAME}/diabetes-logs"
HF_TOKEN = os.getenv("HF_TOKEN")
IST = pytz.timezone('Asia/Kolkata') # Define Timezone

def ensure_dataset_repo():
    try:
        create_repo(DATASET_REPO, token=HF_TOKEN, private=False, repo_type="dataset", exist_ok=True)
        api = HfApi()
        api.upload_file(
            path_or_fileobj="# Diabetes Risk Assessment Logs\nAuto-updated by application.".encode(),
            path_in_repo="README.md",
            repo_id=DATASET_REPO,
            token=HF_TOKEN,
            repo_type="dataset",
        )
    except Exception as e:
        logger.info(f"Repository setup: {e}")

def fetch_remote_logs_via_api(retries: int = 1, delay: float = 0.5) -> pd.DataFrame:
    if HF_TOKEN:
        for attempt in range(retries):
            try:
                local = hf_hub_download(repo_id=DATASET_REPO, filename="audit_log.csv", 
                                       repo_type="dataset", token=HF_TOKEN)
                return pd.read_csv(local, dtype=str)
            except Exception:
                time.sleep(delay)
    try:
        url = f"https://huggingface.co/datasets/{DATASET_REPO}/raw/main/audit_log.csv"
        return pd.read_csv(url, dtype=str)
    except Exception:
        return pd.DataFrame()

def upload_merged_logs(tmp_csv_path: str):
    if not HF_TOKEN:
        raise RuntimeError("Authentication token not configured.")
    api = HfApi()
    api.upload_file(
        path_or_fileobj=str(tmp_csv_path),
        path_in_repo="audit_log.csv",
        repo_id=DATASET_REPO,
        repo_type="dataset",
        token=HF_TOKEN,
        commit_message=f"Update logs {datetime.now(IST).isoformat()}",
        create_pr=False,
    )

@st.cache_resource
def load_resources():
    try:
        model = joblib.load(MODEL_FILE)
        scaler = joblib.load(SCALER_FILE)
        medians = joblib.load(MEDIANS_FILE)
        required = {"Pregnancies", "Glucose", "BloodPressure", "SkinThickness", 
                   "Insulin", "BMI", "DiabetesPedigreeFunction", "Age"}
        if not required.issubset(set(medians.keys())):
            raise ValueError("Configuration error in model files")
        return model, scaler, medians
    except Exception:
        return None, None, None

def validate_inputs(pregnancies, glucose, bloodpressure, skinthickness, insulin, bmi, diabetespedigree, age):
    errors = []
    if not (0 < glucose <= 300): errors.append("Glucose level must be between 1-300 mg/dL")
    if not (0 < bloodpressure <= 200): errors.append("Blood pressure must be between 1-200 mmHg")
    if not (0 < bmi <= 70): errors.append("BMI must be between 1-70")
    if not (0 < age <= 120): errors.append("Age must be between 1-120 years")
    if pregnancies > 20: errors.append("Number of pregnancies cannot exceed 20")
    if age < 15 and pregnancies > 0: errors.append("Age-pregnancy combination is invalid")
    return errors

def predict_diabetes(model, scaler, medians, pregnancies, glucose, bloodpressure, 
                    skinthickness, insulin, bmi, diabetespedigree, age):
    df = pd.DataFrame([{
        "Pregnancies": pregnancies, "Glucose": glucose, "BloodPressure": bloodpressure,
        "SkinThickness": skinthickness, "Insulin": insulin, "BMI": bmi,
        "DiabetesPedigreeFunction": diabetespedigree, "Age": age
    }])
    zero_cols = ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]
    df[zero_cols] = df[zero_cols].replace(0, np.nan)
    df = df.fillna(medians)
    scaled = scaler.transform(df)
    pred = model.predict(scaled)[0]
    prob = model.predict_proba(scaled)[0][1] * 100
    return bool(pred), float(prob)

def log_prediction_remote_only(name: str, inputs: dict, prediction: bool, probability: float):
    logs = fetch_remote_logs_via_api(retries=2, delay=0.3)
    
    # Generate Timestamp in IST
    timestamp_ist = datetime.now(IST).strftime("%Y-%m-%d %H:%M:%S")
    
    new_row = {
        "timestamp": timestamp_ist,
        "name": name or "Anonymous",
        "pregnancies": inputs.get("pregnancies"),
        "glucose": inputs.get("glucose"),
        "bloodpressure": inputs.get("bloodpressure"),
        "skinthickness": inputs.get("skinthickness"),
        "insulin": inputs.get("insulin"),
        "bmi": inputs.get("bmi"),
        "diabetespedigree": inputs.get("diabetespedigree"),
        "age": inputs.get("age"),
        "prediction": "Positive" if prediction else "Negative",
        "probability": f"{probability:.1f}%",
        "region": "India",
    }
    merged = pd.concat([logs, pd.DataFrame([new_row])], ignore_index=True) if not logs.empty else pd.DataFrame([new_row])
    with tempfile.NamedTemporaryFile(mode="w", suffix=".csv", delete=False) as tmpf:
        tmp_path = Path(tmpf.name)
        merged.to_csv(tmp_path, index=False)
    if HF_TOKEN:
        upload_merged_logs(tmp_path)
    try:
        tmp_path.unlink()
    except Exception:
        pass

# 4. Visualization Components

def create_gauge_chart(probability):
    fig = go.Figure(go.Indicator(
        mode="gauge+number",
        value=probability,
        domain={'x': [0, 1], 'y': [0, 1]},
        title={'text': "Risk Probability", 'font': {'size': 16, 'color': '#6B7280'}},
        number={'font': {'size': 40, 'color': '#1F2937'}, 'suffix': '%'},
        gauge={
            'axis': {'range': [None, 100], 'tickwidth': 1, 'tickcolor': "#9CA3AF"},
            'bar': {'color': "#0F52BA"},
            'bgcolor': "white",
            'borderwidth': 2,
            'bordercolor': "#E5E7EB",
            'steps': [
                {'range': [0, 30], 'color': '#D1FAE5'},
                {'range': [30, 60], 'color': '#FEF3C7'},
                {'range': [60, 100], 'color': '#FEE2E2'}
            ],
            'threshold': {'line': {'color': "#EF4444", 'width': 4}, 'thickness': 0.75, 'value': 50}
        }
    ))
    fig.update_layout(paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)', 
                     font={'family': 'Inter'}, height=250, margin=dict(l=20, r=20, t=30, b=20))
    return fig

def create_feature_chart():
    features = ['Glucose', 'BMI', 'Age', 'BP', 'Insulin', 'Pedigree']
    importance = [0.28, 0.22, 0.18, 0.14, 0.10, 0.08]
    fig = go.Figure(go.Bar(
        x=importance, y=features, orientation='h',
        marker=dict(color=importance, colorscale='Blues', showscale=False),
        text=[f'{val:.0%}' for val in importance], textposition='auto',
    ))
    fig.update_layout(
        title="Impact Factors",
        paper_bgcolor='rgba(0,0,0,0)', plot_bgcolor='rgba(0,0,0,0)',
        font={'family': 'Inter', 'color': '#1F2937'},
        xaxis={'showgrid': False, 'visible': False},
        yaxis={'showgrid': False},
        height=300, margin=dict(l=10, r=10, t=40, b=10)
    )
    return fig


# 5. Main Application Logic
def main():
    if "repo_setup" not in st.session_state:
        ensure_dataset_repo()
        st.session_state.repo_setup = True
    if "show_results" not in st.session_state:
        st.session_state.show_results = False

    # Header
    st.markdown("""
    <div class="header-container">
        <span style="background:#0F52BA; color:white; padding:4px 12px; border-radius:20px; font-size:0.75rem; font-weight:600;">CLINICAL AI DEMO v1.0</span>
        <h1 class="header-title" style="margin-top:0.5rem;">Diabetes Risk Assessment</h1>
        <p style="color: #6B7280; margin: 0.5rem 0 0 0;">NIELIT Ropar • Demo for ML Classification</p>
    </div>
    """, unsafe_allow_html=True)

    # Load Model
    model, scaler, medians = load_resources()
    if model is None:
        st.error("⚠️ System Error: Model resources not found.")
        st.stop()

    # Metrics
    logs_df = fetch_remote_logs_via_api(retries=2, delay=0.3)
    total = len(logs_df) if not logs_df.empty else 0
    high = len(logs_df[logs_df['prediction'] == 'Positive']) if not logs_df.empty else 0
    try: avg_bmi = logs_df['bmi'].astype(float).mean() if not logs_df.empty else 0
    except: avg_bmi = 0

    st.markdown(f"""
    <div class="stat-grid">
        <div class="stat-box"><div class="stat-value">{total}</div><div class="stat-label">Total Patients</div></div>
        <div class="stat-box" style="border-left-color: #EF4444;"><div class="stat-value">{high}</div><div class="stat-label">High Risk</div></div>
        <div class="stat-box" style="border-left-color: #10B981;"><div class="stat-value">{avg_bmi:.1f}</div><div class="stat-label">Avg BMI</div></div>
        <div class="stat-box" style="border-left-color: #F59E0B;"><div class="stat-value">92%</div><div class="stat-label">Accuracy</div></div>
    </div>
    """, unsafe_allow_html=True)

    # Main Grid
    col_left, col_right = st.columns([1, 1.2], gap="large")

    with col_left:
        # Form Container
        st.markdown('<div class="content-card"><h3 style="margin:0 0 1rem 0; font-size:1.1rem; color:#111827;">👤 Patient Details</h3>', unsafe_allow_html=True)
        
        with st.form("assessment_form", clear_on_submit=False):
            name = st.text_input("Full Name (Optional)", placeholder="e.g. Anita Budhiraja")
            st.markdown("<div style='margin-bottom:10px;'></div>", unsafe_allow_html=True)
            
            c1, c2 = st.columns(2)
            with c1:
                glucose = st.number_input("Glucose (mg/dL)", 0, 300, value=120)
                bloodpressure = st.number_input("BP (mmHg)", 0, 200, value=80)
                bmi = st.number_input("BMI", 0.0, 70.0, value=25.0, format="%.1f")
                age = st.number_input("Age (years)", 1, 120, value=30)
            with c2:
                pregnancies = st.number_input("Pregnancies", 0, 20, value=0)
                insulin = st.number_input("Insulin", 0, 500, value=0)
                skinthickness = st.number_input("Skin Thickness", 0, 100, value=20)
                diabetespedigree = st.number_input("Pedigree Func", 0.0, 3.0, value=0.5, format="%.3f")

            st.markdown("<br>", unsafe_allow_html=True)
            submitted = st.form_submit_button("Analyze Risk Profile", use_container_width=True)
            
            if submitted:
                inputs = {"pregnancies": pregnancies, "glucose": glucose, "bloodpressure": bloodpressure,
                         "skinthickness": skinthickness, "insulin": insulin, "bmi": bmi,
                         "diabetespedigree": diabetespedigree, "age": age}
                
                errors = validate_inputs(**inputs)
                if errors:
                    st.error(f"Validation Error: {errors[0]}")
                else:
                    with st.spinner("Processing..."):
                        time.sleep(0.5)
                        pred, prob = predict_diabetes(model, scaler, medians, **inputs)
                        if pred is not None:
                            log_prediction_remote_only(name, inputs, pred, prob)
                            st.session_state.show_results = True
                            st.session_state.last_prediction = {"pred": pred, "prob": prob, "name": name}

        st.markdown('</div>', unsafe_allow_html=True)

    with col_right:
        if st.session_state.show_results and "last_prediction" in st.session_state:
            result = st.session_state.last_prediction
            pred, prob, patient_name = result["pred"], result["prob"], result["name"]
            
            # Risk Result
            risk_class = "risk-high" if pred else "risk-low"
            risk_icon = "⚠️" if pred else "✅"
            risk_text = "ELEVATED RISK" if pred else "LOW RISK"
            
            st.markdown(f"""
            <div class="{risk_class}">
                <div style="font-size: 3rem; margin-bottom: 0.5rem;">{risk_icon}</div>
                <h2 style="margin:0; font-size: 1.5rem; font-weight: 700;">{risk_text}</h2>
                <div style="font-size: 1.2rem; opacity: 0.9; margin-top: 0.5rem;">Score: {prob:.1f}%</div>
                <div style="font-size: 0.85rem; opacity: 0.8; margin-top: 1rem; border-top: 1px solid rgba(255,255,255,0.2); padding-top: 0.5rem;">
                    Patient: {patient_name or 'N/A'} • {datetime.now(IST).strftime('%d %b, %H:%M')}
                </div>
            </div>
            """, unsafe_allow_html=True)
            
            # Charts
            st.markdown('<div class="content-card" style="margin-top: 1.5rem;">', unsafe_allow_html=True)
            t1, t2 = st.tabs(["Visualization", "Guidance"])
            with t1:
                g1, g2 = st.columns(2)
                with g1: st.plotly_chart(create_gauge_chart(prob), use_container_width=True, config={'displayModeBar': False})
                with g2: st.plotly_chart(create_feature_chart(), use_container_width=True, config={'displayModeBar': False})
            with t2:
                if pred:
                    st.warning("Recommended: HbA1c test, Endocrinology referral, Lifestyle modification.")
                else:
                    st.success("Recommended: Annual screening, Regular exercise, Balanced diet.")
            st.markdown('</div>', unsafe_allow_html=True)

        else:
            # Welcome State
            st.markdown("""
            <div class="content-card" style="text-align: center; padding: 3rem 1.5rem;">
                <div style="font-size: 3rem; margin-bottom: 1rem;">👋</div>
                <h3 style="color: #1F2937;">Ready for Assessment</h3>
                <p style="color: #6B7280;">Fill out the parameters to generate a report.</p>
            </div>
            """, unsafe_allow_html=True)

            # PROFESSIONAL TABLE UPDATE
            if not logs_df.empty:
                # 1. Header
                st.markdown('<div class="content-card" style="margin-bottom: 0;"><h3 style="margin:0; font-size:1.1rem; color:#111827;">📈 Recent Activity (IST)</h3></div>', unsafe_allow_html=True)
                
                # 2. Data Preparation
                with st.container():
                    # Create clean copy
                    display_df = logs_df.copy()
                    
                    # Convert columns for better sorting/display
                    display_df['timestamp'] = pd.to_datetime(display_df['timestamp'], errors='coerce')
                    # Convert probability "95.5%" string to float 95.5 for progress bar
                    display_df['prob_float'] = display_df['probability'].str.replace('%', '').astype(float)
                    
                    # Map Prediction to pretty text
                    display_df['Risk Status'] = display_df['prediction'].map({
                        'Positive': 'High Risk ⚠️', 
                        'Negative': 'Low Risk ✅'
                    })

                    # Select & Order Columns
                    final_df = display_df[['timestamp', 'name', 'age', 'Risk Status', 'prob_float']].sort_values("timestamp", ascending=False).head(10)

                    # 3. Enterprise Data Grid
                    st.dataframe(
                        final_df,
                        column_config={
                            "timestamp": st.column_config.DatetimeColumn("Date (IST)", format="D MMM, HH:mm"),
                            "name": st.column_config.TextColumn("Patient Name"),
                            "age": st.column_config.NumberColumn("Age"),
                            "Risk Status": st.column_config.TextColumn("Risk Profile"),
                            "prob_float": st.column_config.ProgressColumn(
                                "Risk Score", 
                                format="%.1f%%", 
                                min_value=0, 
                                max_value=100,
                            ),
                        },
                        use_container_width=True,
                        hide_index=True,
                        height=350  # FIXED: Added fixed height to stop shaking loop
                    )

    # Footer
    st.markdown("""
    <div style="text-align:center; padding:2rem; color:#9CA3AF; font-size:0.8rem; border-top:1px solid #E5E7EB; margin-top:2rem;">
        National Institute of Electronics & Information Technology, (Deemed to be University), ROPAR<br>
        <span style="opacity:0.8">Screening tool only. Not a medical diagnosis.</span>
    </div>
    """, unsafe_allow_html=True)

if __name__ == "__main__":
    main()